# Generated by Django 3.1.4 on 2021-01-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='City/Locality Name', max_length=30)),
                ('Property_Type', models.CharField(default='Type', max_length=60)),
                ('Agents', models.CharField(default='Boburbek', max_length=25)),
                ('Beds', models.IntegerField(default=1)),
                ('Bathroom', models.IntegerField(default=1)),
                ('Price', models.CharField(default='Max Price', max_length=10)),
                ('Area', models.CharField(default='Max Area', max_length=30)),
            ],
        ),
    ]
