# Generated by Django 3.1.4 on 2021-02-21 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=1, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('region_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.region')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, null=True)),
                ('location', models.CharField(max_length=30)),
                ('Agents', models.CharField(max_length=25)),
                ('Beds', models.IntegerField(default=1)),
                ('Bathroom', models.IntegerField(default=1)),
                ('Price', models.FloatField()),
                ('image', models.ImageField(upload_to='pictures')),
                ('author', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=30, null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('time_start', models.TimeField(auto_now=True, null=True)),
                ('modum', models.TextField()),
                ('propertType', models.CharField(choices=[('Commericial', 'Commerical'), ('-Office', '-Office'), ('Residential', 'Residential'), ('Villa', 'Villa'), ('Condominium', 'Condominium'), ('Apartment', 'Apartment')], max_length=200, null=True)),
                ('stats', models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale')], max_length=200, null=True)),
                ('Property_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.view')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.district')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.region')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.status')),
            ],
        ),
    ]
