# Generated by Django 3.1.4 on 2021-02-21 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='propertType',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='stats',
        ),
    ]
