# Generated by Django 3.1.4 on 2021-01-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='Area',
        ),
        migrations.AddField(
            model_name='announcement',
            name='imagae',
            field=models.ImageField(default=0, upload_to='pictures'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='Price',
            field=models.IntegerField(),
        ),
    ]
