# Generated by Django 3.1.4 on 2021-02-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20210221_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='Garage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
