# Generated by Django 3.1.4 on 2021-01-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20210112_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='Price',
            field=models.FloatField(),
        ),
    ]
