# Generated by Django 3.1.4 on 2021-03-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20210331_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='Price',
            field=models.PositiveIntegerField(verbose_name='Price'),
        ),
    ]
