# Generated by Django 3.1.4 on 2021-01-27 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20210127_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='see',
            new_name='type',
        ),
    ]
