# Generated by Django 3.1.4 on 2021-01-30 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20210130_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.district'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.region'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.status'),
        ),
    ]
