# Generated by Django 3.1.4 on 2021-01-30 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0007_auto_20210130_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='foydalanuvchi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
