# Generated by Django 3.1.4 on 2021-01-30 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0009_auto_20210130_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='author',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='foydalanuvchi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
