# Generated by Django 3.1.4 on 2021-02-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_auto_20210201_1523'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='type',
            new_name='Property_type',
        ),
        migrations.AddField(
            model_name='announcement',
            name='modum',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='Agents',
            field=models.CharField(max_length=25),
        ),
    ]
