# Generated by Django 3.1.4 on 2021-02-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_auto_20210205_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='foydalanuvchi',
        ),
        migrations.AddField(
            model_name='announcement',
            name='author',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
