# Generated by Django 3.1.4 on 2021-02-10 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_auto_20210208_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='imagae',
            new_name='image',
        ),
    ]
