# Generated by Django 3.1.4 on 2021-03-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accaounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='author_image',
            field=models.ImageField(blank=True, default='author_image/author.jpg', null=True, upload_to='author_image'),
        ),
    ]
